name: "Setup Continuous Integration"
description: "Cache Dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"

    - name: Cache NPM Dependencies
      uses: actions/cache@v3
      id: cache-primes
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install
      shell: bash

    - name: "Create env file"
        run: |
          touch .env
          echo CONVEX_DEPLOYMENT=${{ secrets.CONVEX_DEPLOYMENT }} >> .env
          echo NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} >> .env 
          echo NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }} >> .env
          echo LIVEBLOCKS_SECRET_API_KEY=${{ secrets.LIVEBLOCKS_SECRET_API_KEY }} >> .env
          echo CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} >> .env
          cat .env