import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "sonner";

import ConvexClientProvider from "@/components/providers/convex-client-provider";
import ModelProvider from "@/components/providers/model-provider";
import Loading from "./board/[boardId]/_components/loading";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <ConvexClientProvider>
            {children}
            <Toaster />
            <ModelProvider />
          </ConvexClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
